export { default as HomeHeader } from '../components/home-header.vue'
export { default as HomeHero } from '../components/home-hero.vue'
export { default as HomeBenefits } from '../components/home-benefits.vue'
export { default as HomeMotivation } from '../components/home-motivation.vue'
export { default as HomeWorkflow } from '../components/home-workflow.vue'
export { default as HomeContact } from '../components/home-contact.vue'
export { default as HomeFooter } from '../components/home-footer.vue'